image: mcr.microsoft.com/dotnet/sdk:8.0

definitions:
  services:
    docker:
      memory: 2048
  steps:
    - step: &publish-step
        name: Publish docker image
        size: 2x
        script:
          - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
          - docker build --build-arg PACKAGE_VERSION=$BITBUCKET_BUILD_NUMBER -f snglrtycrvtureofspce.Animal/Dockerfile -t snglrtycrvtureofspce/$BITBUCKET_REPO_SLUG.net:$BITBUCKET_BUILD_NUMBER .
          - docker push snglrtycrvtureofspce/$BITBUCKET_REPO_SLUG.net:$BITBUCKET_BUILD_NUMBER
        services:
          - docker
    - step: &test-step
        name: Run tests
        size: 2x
        script:
          - dotnet restore
          - dotnet build
          - dotnet test --logger "junit;LogFilePath=./test-reports/results.xml"
        services:
          - docker
    - step: &update-container-step
        deployment: Staging
        name: Update container
        script:
          - curl -X POST https://localhost:9443/api/webhooks/12a62a3d-d51d-42d5-a321-30781d59a8f4?tag=$BITBUCKET_BUILD_NUMBER

pipelines:
  branches:
    master:
      - step: *test-step
      - step: *publish-step
      - step: *update-container-step
    default:
      - step: *test-step